---
image: gcr.io/prysmaticlabs/prysm/validator
imageTag: latest

config:
  datadir: /data/
  p2p-host-ip: 
  p2p-tcp-port: 13000
  beacon-rpc-provider: "beacon-client:4000"
  log-file: /data/validator.log
  verbosity: debug

storage:
  capacity: "20Gi"

resources:
  limits:
    memory: "2Gi"
  requests:
    memory: "2Gi"