---
apiVersion: v1
kind: Service
metadata:
  name: beacon-service
  labels: 
    app: beacon-client
spec:
  selector:
    app: beacon-client
  ports:
    - protocol: TCP
      port: {{ (index .Values "config" "p2p-tcp-port") | default 13000 }}
      name: p2p-tcp
    - protocol: UDP
      port: {{ (index .Values "config" "p2p-udp-port") | default 12000 }}
      name: p2p-udp
    - protocol: TCP
      port: {{ (index .Values "config" "monitoring-port") | default 8080 }}
      name: monitoring

{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beacon-config
data:
  beacon-client.yaml: |
{{ toYaml .Values.config | indent 4 }}
{{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beacon-client
spec:
  selector:
    matchLabels:
      app: beacon-client
  serviceName: beacon-service
  replicas: 1
  template:
    metadata:
      labels:
        app: beacon-client
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: beacon-client
          image: "{{ .Values.image }}:{{ .Values.imageTag | default "latest" }}"
          {{- if .Values.config }}
          args: ["--config-file","/host/config/beacon-client.yaml"]
          {{- end }}
          resources: 
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            failureThreshold: 60
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: beacon-data-storage
              mountPath: /host
            {{- if .Values.config }}
            - name: config-volume
              mountPath: /host/config
            {{- end }}
          ports:
            - name: p2p-tcp
              containerPort: {{ (index .Values "config" "p2p-tcp-port") | default 13000 }}
            - name: p2p-udp
              containerPort: {{ (index .Values "config" "p2p-udp-port") | default 12000 }}
            - name: monitoring
              containerPort: {{ (index .Values "config" "monitoring-port") | default 8080 }}
      volumes:
        {{- if .Values.config }}
        - name: config-volume
          configMap:
            name: beacon-config
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: beacon-data-storage
      spec:
        storageClassName: manual
        accessModes: 
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.storage.capacity | quote }}